// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea3RegPrestamo.DAL;

namespace Tarea3RegPrestamo.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Tarea3RegPrestamo.Models.Mora", b =>
                {
                    b.Property<int>("MoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("MoraId");

                    b.ToTable("moras");
                });

            modelBuilder.Entity("Tarea3RegPrestamo.Models.MoraDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrestamosId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("DetalleId");

                    b.HasIndex("MoraId");

                    b.HasIndex("PrestamosId");

                    b.ToTable("MoraDetalle");
                });

            modelBuilder.Entity("Tarea3RegPrestamo.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Normbre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telofono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.HasKey("PersonaId");

                    b.ToTable("personas");

                    b.HasData(
                        new
                        {
                            PersonaId = 1,
                            Balance = 10m,
                            Cedula = "789-9632598-1",
                            Direccion = "C/ Maximo Gomez, Casa#3",
                            FechaNacimiento = new DateTime(2020, 7, 11, 12, 17, 30, 348, DateTimeKind.Local).AddTicks(2956),
                            Normbre = "Steven Caceres",
                            Telofono = "829-635-5478"
                        },
                        new
                        {
                            PersonaId = 10,
                            Balance = 10m,
                            Cedula = "789-9632598-1",
                            Direccion = "C/ Maximo Gomez, Casa#3",
                            FechaNacimiento = new DateTime(2020, 7, 11, 12, 17, 30, 351, DateTimeKind.Local).AddTicks(2397),
                            Normbre = "Steven Nunez",
                            Telofono = "829-635-5478"
                        });
                });

            modelBuilder.Entity("Tarea3RegPrestamo.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balances")
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrestamoId");

                    b.ToTable("prestamos");

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            Balances = 15m,
                            Concepto = "Terreno",
                            FechaPrestamo = new DateTime(2020, 7, 11, 12, 17, 30, 351, DateTimeKind.Local).AddTicks(6199),
                            Monto = 15m,
                            PersonaId = 1
                        });
                });

            modelBuilder.Entity("Tarea3RegPrestamo.Models.MoraDetalle", b =>
                {
                    b.HasOne("Tarea3RegPrestamo.Models.Mora", null)
                        .WithMany("moradetalles")
                        .HasForeignKey("MoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tarea3RegPrestamo.Models.Prestamos", "prestamos")
                        .WithMany()
                        .HasForeignKey("PrestamosId");
                });
#pragma warning restore 612, 618
        }
    }
}
